// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLgZEvuj9zpf5SpiYXn4s3wWp7Pu2gcXE',
    appId: '1:290685477286:web:efb16bdbbd8c634f84ef67',
    messagingSenderId: '290685477286',
    projectId: 'servxfactory',
    authDomain: 'servxfactory.firebaseapp.com',
    storageBucket: 'servxfactory.firebasestorage.app',
    measurementId: 'G-2D6MYKZL09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbKYjE2JFa_f9irR1nS5_yaSYZfFnEOJU',
    appId: '1:290685477286:android:ddab2b4bf70b698e84ef67',
    messagingSenderId: '290685477286',
    projectId: 'servxfactory',
    storageBucket: 'servxfactory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5n5abv1FGhnNcvQudScuBclDEtEonGOI',
    appId: '1:290685477286:ios:70fffaf93966794784ef67',
    messagingSenderId: '290685477286',
    projectId: 'servxfactory',
    storageBucket: 'servxfactory.firebasestorage.app',
    iosBundleId: 'com.example.ServXFactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5n5abv1FGhnNcvQudScuBclDEtEonGOI',
    appId: '1:290685477286:ios:70fffaf93966794784ef67',
    messagingSenderId: '290685477286',
    projectId: 'servxfactory',
    storageBucket: 'servxfactory.firebasestorage.app',
    iosBundleId: 'com.example.ServXFactory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLgZEvuj9zpf5SpiYXn4s3wWp7Pu2gcXE',
    appId: '1:290685477286:web:5067140b15eca4f284ef67',
    messagingSenderId: '290685477286',
    projectId: 'servxfactory',
    authDomain: 'servxfactory.firebaseapp.com',
    storageBucket: 'servxfactory.firebasestorage.app',
    measurementId: 'G-BK6Y28WF1P',
  );
}
